version: '1.0'
services:
  forum-postgresql:
    image: bitnami/postgresql
    restart: always
    environment:
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: postgres
    ports:
    - '5432:5432'
  forum:
    image: lexhigh/forum
    restart: always
    ports:
    - '8080:8080'
    logging:
      options:
        max-size: "10m"
        max-file: "10"
